export const BOX_SIZING_MAP = {
  content: "box-content",
  border: "box-border",
};

export const BOX_DISPLAY_MAP = {
  flex: "flex",
  grid: "grid",
  block: "block",
  inline: "inline",
  hidden: "hidden",
  flowRoot: "flow-root",
  contents: "contents",
  inlineBlock: "inline-block",
  inlineFlex: "inline-flex",
  inlineGrid: "inline-grid",
};

export const CONTENT_POSITION_MAP = {
  static: "static",
  fixed: "fixed",
  absolute: "absolute",
  relative: "relative",
  sticky: "sticky",
};

export const FIXED_PLACEMENT_MAP = {
  "top-xxs": "top-0",
  "top-xs": "top-4",
  "top-sm": "top-8",
  "top-md": "top-16",
  "top-lg": "top-24",
  "top-xl": "top-48",
  "top-xxl": "top-96",
  "right-xxs": "right-0",
  "right-xs": "right-4",
  "right-sm": "right-8",
  "right-md": "right-16",
  "right-lg": "right-24",
  "right-xl": "right-48",
  "right-xxl": "right-96",
  "bottom-xxs": "bottom-0",
  "bottom-xs": "bottom-4",
  "bottom-sm": "bottom-8",
  "bottom-md": "bottom-16",
  "bottom-lg": "bottom-24",
  "bottom-xl": "bottom-48",
  "bottom-xxl": "bottom-96",
  "left-xxs": "left-0",
  "left-xs": "left-4",
  "left-sm": "left-8",
  "left-md": "left-16",
  "left-lg": "left-24",
  "left-xl": "left-48",
  "left-xxl": "left-96",
};

export const FIXED_LOGICAL_PLACEMENT_MAP = {
  "inset-xxs": "inset-0",
  "inset-xs": "inset-4",
  "inset-sm": "inset-8",
  "inset-md": "inset-16",
  "inset-lg": "inset-24",
  "inset-xl": "inset-48",
  "inset-xxl": "inset-96",
  "start-xxs": "start-0",
  "start-xs": "start-4",
  "start-sm": "start-8",
  "start-md": "start-16",
  "start-lg": "start-24",
  "start-xl": "start-48",
  "start-xxl": "start-96",
  "end-xxs": "end-0",
  "end-xs": "end-4",
  "end-sm": "end-8",
  "end-md": "end-16",
  "end-lg": "end-24",
  "end-xl": "end-48",
  "end-xxl": "end-96",
};

export const FIXED_GAP_MAP = {
  xxs: "gap-0.5",
  xs: "gap-1",
  sm: "gap-2",
  md: "gap-4",
  lg: "gap-8",
  xl: "gap-16",
  xxl: "gap-24",
};
