export const FIXED_SPACING_MAP = {
  "x-xxs": "space-x-0.5",
  "x-xs": "space-x-1",
  "x-sm": "space-x-2",
  "x-md": "space-x-4",
  "x-lg": "space-x-8",
  "x-xl": "space-x-16",
  "x-xxl": "space-x-24",
  "y-xxs": "space-y-0.5",
  "y-xs": "space-y-1",
  "y-sm": "space-y-2",
  "y-md": "space-y-4",
  "y-lg": "space-y-8",
  "y-xl": "space-y-16",
  "y-xxl": "space-y-24",
};

export const NEGATIVE_FIXED_SPACING_MAP = {
  "-x-xxs": "-space-x-0.5",
  "-x-xs": "-space-x-1",
  "-x-sm": "-space-x-2",
  "-x-md": "-space-x-4",
  "-x-lg": "-space-x-8",
  "-x-xl": "-space-x-16",
  "-x-xxl": "-space-x-24",
  "-y-xxs": "-space-y-0.5",
  "-y-xs": "-space-y-1",
  "-y-sm": "-space-y-2",
  "-y-md": "-space-y-4",
  "-y-lg": "-space-y-8",
  "-y-xl": "-space-y-16",
  "-y-xxl": "-space-y-24",
};

export const FIXED_MARGIN_MAP = {
  xxs: "m-0.5",
  xs: "m-1",
  sm: "m-2",
  md: "m-4",
  lg: "m-8",
  xl: "m-16",
  xxl: "m-24",
};

export const FIXED_PADDING_MAP = {
  xxs: "p-0.5",
  xs: "p-1",
  sm: "p-2",
  md: "p-4",
  lg: "p-8",
  xl: "p-16",
  xxl: "p-24",
};

export const FIXED_SIDES_PADDING_MAP = {
  "top-xxs": "pt-0.5",
  "top-xs": "pt-4",
  "top-sm": "pt-8",
  "top-md": "pt-16",
  "top-lg": "pt-24",
  "top-xl": "pt-48",
  "top-xxl": "pt-96",
  "right-xxs": "pr-0.5",
  "right-xs": "pr-4",
  "right-sm": "pr-8",
  "right-md": "pr-16",
  "right-lg": "pr-24",
  "right-xl": "pr-48",
  "right-xxl": "pr-96",
  "bottom-xxs": "pb-0.5",
  "bottom-xs": "pb-4",
  "bottom-sm": "pb-8",
  "bottom-md": "pb-16",
  "bottom-lg": "pb-24",
  "bottom-xl": "pb-48",
  "bottom-xxl": "pb-96",
  "left-xxs": "pk-0.5",
  "left-xs": "pl-4",
  "left-sm": "pl-8",
  "left-md": "pl-16",
  "left-lg": "pl-24",
  "left-xl": "pl-48",
  "left-xxl": "pl-96",
};

export const FIXED_AXIS_PADDING_MAP = {
  "x-xxs": "px-0.5",
  "x-xs": "px-4",
  "x-sm": "px-8",
  "x-md": "px-16",
  "x-lg": "px-24",
  "x-xl": "px-48",
  "x-xxl": "px-96",
  "y-xxs": "py-0",
  "y-xs": "py-4",
  "y-sm": "py-8",
  "y-md": "py-16",
  "y-lg": "py-24",
  "y-xl": "py-48",
  "y-xxl": "py-96",
};

export const FIXED_LOGICAL_PADDING_MAP = {
  "start-xxs": "ps-0.5",
  "start-xs": "ps-4",
  "start-sm": "ps-8",
  "start-md": "ps-16",
  "start-lg": "ps-24",
  "start-xl": "ps-48",
  "start-xxl": "ps-96",
  "end-xxs": "pe-0.5",
  "end-xs": "pe-4",
  "end-sm": "pe-8",
  "end-md": "pe-16",
  "end-lg": "pe-24",
  "end-xl": "pe-48",
  "end-xxl": "pe-96",
};

export const FIXED_SIDES_MARGIN_MAP = {
  "top-xxs": "mt-0.5",
  "top-xs": "mt-4",
  "top-sm": "mt-8",
  "top-md": "mt-16",
  "top-lg": "mt-24",
  "top-xl": "mt-48",
  "top-xxl": "mt-96",
  "right-xxs": "mr-0.5",
  "right-xs": "mr-4",
  "right-sm": "mr-8",
  "right-md": "mr-16",
  "right-lg": "mr-24",
  "right-xl": "mr-48",
  "right-xxl": "mr-96",
  "bottom-xxs": "mb-0.5",
  "bottom-xs": "mb-4",
  "bottom-sm": "mb-8",
  "bottom-md": "mb-16",
  "bottom-lg": "mb-24",
  "bottom-xl": "mb-48",
  "bottom-xxl": "mb-96",
  "left-xxs": "ml-0.5",
  "left-xs": "ml-4",
  "left-sm": "ml-8",
  "left-md": "ml-16",
  "left-lg": "ml-24",
  "left-xl": "ml-48",
  "left-xxl": "ml-96",
};

export const FIXED_AXIS_MARGIN_MAP = {
  "x-xxs": "mx-0.5",
  "x-xs": "mx-4",
  "x-sm": "mx-8",
  "x-md": "mx-16",
  "x-lg": "mx-24",
  "x-xl": "mx-48",
  "x-xxl": "mx-96",
  "y-xxs": "my-0.5",
  "y-xs": "my-4",
  "y-sm": "my-8",
  "y-md": "my-16",
  "y-lg": "my-24",
  "y-xl": "my-48",
  "y-xxl": "my-96",
};

export const FIXED_LOGICAL_MARGIN_MAP = {
  "start-xxs": "ms-0.5",
  "start-xs": "ms-4",
  "start-sm": "ms-8",
  "start-md": "ms-16",
  "start-lg": "ms-24",
  "start-xl": "ms-48",
  "start-xxl": "ms-96",
  "end-xxs": "me-0.5",
  "end-xs": "me-4",
  "end-sm": "me-8",
  "end-md": "me-16",
  "end-lg": "me-24",
  "end-xl": "me-48",
  "end-xxl": "me-96",
};

export const NEGATIVE_FIXED_SIDES_MARGIN_MAP = {
  "-top-xxs": "-mt-0.5",
  "-top-xs": "-mt-4",
  "-top-sm": "-mt-8",
  "-top-md": "-mt-16",
  "-top-lg": "-mt-24",
  "-top-xl": "-mt-48",
  "-top-xxl": "-mt-96",
  "-right-xxs": "-mr-0.5",
  "-right-xs": "-mr-4",
  "-right-sm": "-mr-8",
  "-right-md": "-mr-16",
  "-right-lg": "-mr-24",
  "-right-xl": "-mr-48",
  "-right-xxl": "-mr-96",
  "-bottom-xxs": "-mb-0.5",
  "-bottom-xs": "-mb-4",
  "-bottom-sm": "-mb-8",
  "-bottom-md": "-mb-16",
  "-bottom-lg": "-mb-24",
  "-bottom-xl": "-mb-48",
  "-bottom-xxl": "-mb-96",
  "-left-xxs": "-ml-0.5",
  "-left-xs": "-ml-4",
  "-left-sm": "-ml-8",
  "-left-md": "-ml-16",
  "-left-lg": "-ml-24",
  "-left-xl": "-ml-48",
  "-left-xxl": "-ml-96",
};

export const NEGATIVE_FIXED_AXIS_MARGIN_MAP = {
  "-x-xxs": "-mx-0.5",
  "-x-xs": "-mx-4",
  "-x-sm": "-mx-8",
  "-x-md": "-mx-16",
  "-x-lg": "-mx-24",
  "-x-xl": "-mx-48",
  "-x-xxl": "-mx-96",
  "-y-xxs": "-my-0.5",
  "-y-xs": "-my-4",
  "-y-sm": "-my-8",
  "-y-md": "-my-16",
  "-y-lg": "-my-24",
  "-y-xl": "-my-48",
  "-y-xxl": "-my-96",
};

export const NEGATIVE_FIXED_LOGICAL_MARGIN_MAP = {
  "-start-xxs": "-ms-0.5",
  "-start-xs": "-ms-4",
  "-start-sm": "-ms-8",
  "-start-md": "-ms-16",
  "-start-lg": "-ms-24",
  "-start-xl": "-ms-48",
  "-start-xxl": "-ms-96",
  "-end-xxs": "-me-0.5",
  "-end-xs": "-me-4",
  "-end-sm": "-me-8",
  "-end-md": "-me-16",
  "-end-lg": "-me-24",
  "-end-xl": "-me-48",
  "-end-xxl": "-me-96",
};
