export const COLOR_MAP  = {
  "mugi" : "text-mugi-400",
  "hat" : "text-hat-400",
  "slate" : "text-slate-400",
  "gray" : "text-gray-400",
  "zinc" : "text-zinc-400",
  "neutral" : "text-neutral-400",
  "stone" : "text-stone-400",
  "red" : "text-red-400",
  "orange" : "text-orange-400",
  "yellow" : "text-yellow-400",
  "amber" : "text-amber-400",
  "lime" : "text-lime-400",
  "green" : "text-green-400",
  "emerald" : "text-emerald-400",
  "teal" : "text-teal-400",
  "cyan" : "text-cyan-400",
  "sky" : "text-sky-400",
  "blue" : "text-blue-400",
  "indigo" : "text-indigo-400",
  "violet" : "text-violet-400",
  "purple" : "text-purple-400",
  "fuchsia" : "text-fuchsia-400",
  "pink" : "text-pink-400",
  "rose" : "text-rose-400",
}

export const BACKGROUND_COLOR_MAP = {
  "mugi" : "bg-mugi-400",
  "hat" : "bg-hat-400",
  "slate" : "bg-slate-400",
  "gray" : "bg-gray-400",
  "zinc" : "bg-zinc-400",
  "neutral" : "bg-neutral-400",
  "stone" : "bg-stone-400",
  "red" : "bg-red-400",
  "orange" : "bg-orange-400",
  "yellow" : "bg-yellow-400",
  "amber" : "bg-amber-400",
  "lime" : "bg-lime-400",
  "green" : "bg-green-400",
  "emerald" : "bg-emerald-400",
  "teal" : "bg-teal-400",
  "cyan" : "bg-cyan-400",
  "sky" : "bg-sky-400",
  "blue" : "bg-blue-400",
  "indigo" : "bg-indigo-400",
  "violet" : "bg-violet-400",
  "purple" : "bg-purple-400",
  "fuchsia" : "bg-fuchsia-400",
  "pink" : "bg-pink-400",
  "rose" : "bg-rose-400",
}

export const DECORATION_COLOR_MAP = {
  "mugi" : "decoration-mugi-400",
  "hat" : "decoration-hat-400",
  "slate" : "decoration-slate-400",
  "gray" : "decoration-gray-400",
  "zinc" : "decoration-zinc-400",
  "neutral" : "decoration-neutral-400",
  "stone" : "decoration-stone-400",
  "red" : "decoration-red-400",
  "orange" : "decoration-orange-400",
  "yellow" : "decoration-yellow-400",
  "amber" : "decoration-amber-400",
  "lime" : "decoration-lime-400",
  "green" : "decoration-green-400",
  "emerald" : "decoration-emerald-400",
  "teal" : "decoration-teal-400",
  "cyan" : "decoration-cyan-400",
  "sky" : "decoration-sky-400",
  "blue" : "decoration-blue-400",
  "indigo" : "decoration-indigo-400",
  "violet" : "decoration-violet-400",
  "purple" : "decoration-purple-400",
  "fuchsia" : "decoration-fuchsia-400",
  "pink" : "decoration-pink-400",
  "rose" : "decoration-rose-400",
}

export const BORDER_COLOR_MAP = {
  "mugi" : "border-mugi-400",
  "hat" : "border-hat-400",
  "slate" : "border-slate-400",
  "gray" : "border-gray-400",
  "zinc" : "border-zinc-400",
  "neutral" : "border-neutral-400",
  "stone" : "border-stone-400",
  "red" : "border-red-400",
  "orange" : "border-orange-400",
  "yellow" : "border-yellow-400",
  "amber" : "border-amber-400",
  "lime" : "border-lime-400",
  "green" : "border-green-400",
  "emerald" : "border-emerald-400",
  "teal" : "border-teal-400",
  "cyan" : "border-cyan-400",
  "sky" : "border-sky-400",
  "blue" : "border-blue-400",
  "indigo" : "border-indigo-400",
  "violet" : "border-violet-400",
  "purple" : "border-purple-400",
  "fuchsia" : "border-fuchsia-400",
  "pink" : "border-pink-400",
  "rose" : "border-rose-400",
}

export const OUTLINE_COLOR_MAP = {
  "mugi" : "outline-mugi-400",
  "hat" : "outline-hat-400",
  "slate" : "outline-slate-400",
  "gray" : "outline-gray-400",
  "zinc" : "outline-zinc-400",
  "neutral" : "outline-neutral-400",
  "stone" : "outline-stone-400",
  "red" : "outline-red-400",
  "orange" : "outline-orange-400",
  "yellow" : "outline-yellow-400",
  "amber" : "outline-amber-400",
  "lime" : "outline-lime-400",
  "green" : "outline-green-400",
  "emerald" : "outline-emerald-400",
  "teal" : "outline-teal-400",
  "cyan" : "outline-cyan-400",
  "sky" : "outline-sky-400",
  "blue" : "outline-blue-400",
  "indigo" : "outline-indigo-400",
  "violet" : "outline-violet-400",
  "purple" : "outline-purple-400",
  "fuchsia" : "outline-fuchsia-400",
  "pink" : "outline-pink-400",
  "rose" : "outline-rose-400",
}

export const SHADOW_COLOR_MAP = {
  "mugi" : "shadow-mugi-400",
  "hat" : "shadow-hat-400",
  "slate" : "shadow-slate-400",
  "gray" : "shadow-gray-400",
  "zinc" : "shadow-zinc-400",
  "neutral" : "shadow-neutral-400",
  "stone" : "shadow-stone-400",
  "red" : "shadow-red-400",
  "orange" : "shadow-orange-400",
  "yellow" : "shadow-yellow-400",
  "amber" : "shadow-amber-400",
  "lime" : "shadow-lime-400",
  "green" : "shadow-green-400",
  "emerald" : "shadow-emerald-400",
  "teal" : "shadow-teal-400",
  "cyan" : "shadow-cyan-400",
  "sky" : "shadow-sky-400",
  "blue" : "shadow-blue-400",
  "indigo" : "shadow-indigo-400",
  "violet" : "shadow-violet-400",
  "purple" : "shadow-purple-400",
  "fuchsia" : "shadow-fuchsia-400",
  "pink" : "shadow-pink-400",
  "rose" : "shadow-rose-400",
}

export const INSET_SHADOW_COLOR_MAP = {
  "mugi" : "inset-shadow-mugi-400",
  "hat" : "inset-shadow-hat-400",
  "slate" : "inset-shadow-slate-400",
  "gray" : "inset-shadow-gray-400",
  "zinc" : "inset-shadow-zinc-400",
  "neutral" : "inset-shadow-neutral-400",
  "stone" : "inset-shadow-stone-400",
  "red" : "inset-shadow-red-400",
  "orange" : "inset-shadow-orange-400",
  "yellow" : "inset-shadow-yellow-400",
  "amber" : "inset-shadow-amber-400",
  "lime" : "inset-shadow-lime-400",
  "green" : "inset-shadow-green-400",
  "emerald" : "inset-shadow-emerald-400",
  "teal" : "inset-shadow-teal-400",
  "cyan" : "inset-shadow-cyan-400",
  "sky" : "inset-shadow-sky-400",
  "blue" : "inset-shadow-blue-400",
  "indigo" : "inset-shadow-indigo-400",
  "violet" : "inset-shadow-violet-400",
  "purple" : "inset-shadow-purple-400",
  "fuchsia" : "inset-shadow-fuchsia-400",
  "pink" : "inset-shadow-pink-400",
  "rose" : "inset-shadow-rose-400",
}

export const RING_COLOR_MAP = {
  "mugi" : "ring-mugi-400",
  "hat" : "ring-hat-400",
  "slate" : "ring-slate-400",
  "gray" : "ring-gray-400",
  "zinc" : "ring-zinc-400",
  "neutral" : "ring-neutral-400",
  "stone" : "ring-stone-400",
  "red" : "ring-red-400",
  "orange" : "ring-orange-400",
  "yellow" : "ring-yellow-400",
  "amber" : "ring-amber-400",
  "lime" : "ring-lime-400",
  "green" : "ring-green-400",
  "emerald" : "ring-emerald-400",
  "teal" : "ring-teal-400",
  "cyan" : "ring-cyan-400",
  "sky" : "ring-sky-400",
  "blue" : "ring-blue-400",
  "indigo" : "ring-indigo-400",
  "violet" : "ring-violet-400",
  "purple" : "ring-purple-400",
  "fuchsia" : "ring-fuchsia-400",
  "pink" : "ring-pink-400",
  "rose" : "ring-rose-400",
}

export const INSET_RING_COLOR_MAP = {
  "mugi" : "inset-ring-mugi-400",
  "hat" : "inset-ring-hat-400",
  "slate" : "inset-ring-slate-400",
  "gray" : "inset-ring-gray-400",
  "zinc" : "inset-ring-zinc-400",
  "neutral" : "inset-ring-neutral-400",
  "stone" : "inset-ring-stone-400",
  "red" : "inset-ring-red-400",
  "orange" : "inset-ring-orange-400",
  "yellow" : "inset-ring-yellow-400",
  "amber" : "inset-ring-amber-400",
  "lime" : "inset-ring-lime-400",
  "green" : "inset-ring-green-400",
  "emerald" : "inset-ring-emerald-400",
  "teal" : "inset-ring-teal-400",
  "cyan" : "inset-ring-cyan-400",
  "sky" : "inset-ring-sky-400",
  "blue" : "inset-ring-blue-400",
  "indigo" : "inset-ring-indigo-400",
  "violet" : "inset-ring-violet-400",
  "purple" : "inset-ring-purple-400",
  "fuchsia" : "inset-ring-fuchsia-400",
  "pink" : "inset-ring-pink-400",
  "rose" : "inset-ring-rose-400",
}

export const ACCENT_COLOR_MAP = {
  "mugi" : "accent-mugi-400",
  "hat" : "accent-hat-400",
  "slate" : "accent-slate-400",
  "gray" : "accent-gray-400",
  "zinc" : "accent-zinc-400",
  "neutral" : "accent-neutral-400",
  "stone" : "accent-stone-400",
  "red" : "accent-red-400",
  "orange" : "accent-orange-400",
  "yellow" : "accent-yellow-400",
  "amber" : "accent-amber-400",
  "lime" : "accent-lime-400",
  "green" : "accent-green-400",
  "emerald" : "accent-emerald-400",
  "teal" : "accent-teal-400",
  "cyan" : "accent-cyan-400",
  "sky" : "accent-sky-400",
  "blue" : "accent-blue-400",
  "indigo" : "accent-indigo-400",
  "violet" : "accent-violet-400",
  "purple" : "accent-purple-400",
  "fuchsia" : "accent-fuchsia-400",
  "pink" : "accent-pink-400",
  "rose" : "accent-rose-400",
}

export const CARET_COLOR_MAP = {
  "mugi" : "caret-mugi-400",
  "hat" : "caret-hat-400",
  "slate" : "caret-slate-400",
  "gray" : "caret-gray-400",
  "zinc" : "caret-zinc-400",
  "neutral" : "caret-neutral-400",
  "stone" : "caret-stone-400",
  "red" : "caret-red-400",
  "orange" : "caret-orange-400",
  "yellow" : "caret-yellow-400",
  "amber" : "caret-amber-400",
  "lime" : "caret-lime-400",
  "green" : "caret-green-400",
  "emerald" : "caret-emerald-400",
  "teal" : "caret-teal-400",
  "cyan" : "caret-cyan-400",
  "sky" : "caret-sky-400",
  "blue" : "caret-blue-400",
  "indigo" : "caret-indigo-400",
  "violet" : "caret-violet-400",
  "purple" : "caret-purple-400",
  "fuchsia" : "caret-fuchsia-400",
  "pink" : "caret-pink-400",
  "rose" : "caret-rose-400",
}

export const FILL_COLOR_MAP = {
  "mugi" : "fill-mugi-400",
  "hat" : "fill-hat-400",
  "slate" : "fill-slate-400",
  "gray" : "fill-gray-400",
  "zinc" : "fill-zinc-400",
  "neutral" : "fill-neutral-400",
  "stone" : "fill-stone-400",
  "red" : "fill-red-400",
  "orange" : "fill-orange-400",
  "yellow" : "fill-yellow-400",
  "amber" : "fill-amber-400",
  "lime" : "fill-lime-400",
  "green" : "fill-green-400",
  "emerald" : "fill-emerald-400",
  "teal" : "fill-teal-400",
  "cyan" : "fill-cyan-400",
  "sky" : "fill-sky-400",
  "blue" : "fill-blue-400",
  "indigo" : "fill-indigo-400",
  "violet" : "fill-violet-400",
  "purple" : "fill-purple-400",
  "fuchsia" : "fill-fuchsia-400",
  "pink" : "fill-pink-400",
  "rose" : "fill-rose-400",
}

export const STROKE_COLOR_MAP = {
  "mugi" : "stroke-mugi-400",
  "hat" : "stroke-hat-400",
  "slate" : "stroke-slate-400",
  "gray" : "stroke-gray-400",
  "zinc" : "stroke-zinc-400",
  "neutral" : "stroke-neutral-400",
  "stone" : "stroke-stone-400",
  "red" : "stroke-red-400",
  "orange" : "stroke-orange-400",
  "yellow" : "stroke-yellow-400",
  "amber" : "stroke-amber-400",
  "lime" : "stroke-lime-400",
  "green" : "stroke-green-400",
  "emerald" : "stroke-emerald-400",
  "teal" : "stroke-teal-400",
  "cyan" : "stroke-cyan-400",
  "sky" : "stroke-sky-400",
  "blue" : "stroke-blue-400",
  "indigo" : "stroke-indigo-400",
  "violet" : "stroke-violet-400",
  "purple" : "stroke-purple-400",
  "fuchsia" : "stroke-fuchsia-400",
  "pink" : "stroke-pink-400",
  "rose" : "stroke-rose-400",
}